/** Exact teaching functions; changes and differentials are kept separate. */
const slider=(key,label,min,max,step)=>({key,label,min,max,step});
const choice=(key,label,options)=>({key,label,options});
export const lessons=[
 {id:'slope',title:'Catch a slope',verb:'Move → shrink → compare',intro:'A derivative tells you how much the output responds to a tiny move. Put two probes on the curve, then bring them together.',defaults:{fn:'square',x:1,h:.8},controls:[choice('fn','Function',[['square','x²'],['sin','sin x'],['exp','eˣ'],['abs','|x| · a corner']]),slider('x','Starting point, x',-2,2,.05),slider('h','Move size, Δx',.01,1,.01)],action:'Shrink the move',tip:'Try |x| at x = 0. The left and right slopes disagree, however close you zoom.',question:'At the corner of |x|, which derivative is correct?',answers:['−1','0','It does not exist'],correct:2,feedback:'The left slope is −1 and the right slope is +1. A symmetric difference of zero would hide the corner.',formal:String.raw`f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}`,advanced:'A derivative is a local linear map: f(x+h)=f(x)+f′(x)h+o(|h|). A plotted finite difference is evidence about the limit, not the limit itself. At a corner there is no single linear approximation valid from both sides.'},
 {id:'product',title:'Grow a rectangle',verb:'Stretch → split → account',intro:'Both sides depend on x. Growing the rectangle adds two strips and a small corner. The product rule counts the strips.',defaults:{x:2,h:.6},controls:[slider('x','Short side, x',.5,3,.05),slider('h','Growth of each side, Δx',.01,1,.01)],action:'Shrink the corner',tip:'Halve Δx: the strips roughly halve, but the corner quarters. Its contribution per unit Δx disappears in the limit.',question:'Why is the derivative of x(x+1) not just 1 × 1?',answers:['Only one side changes','Both side changes contribute','The corner stays dominant'],correct:1,feedback:'The first-order changes are (x+1)Δx and xΔx. Divide by Δx and let it shrink: (x+1)+x=2x+1.',formal:String.raw`\Delta[uv]=v\Delta u+u\Delta v+\Delta u\Delta v,\qquad (uv)'=u'v+uv'`,advanced:'For u=x and v=x+1, the leftover is exactly (Δx)². The same argument extends to differentiable u and v because their increments are first order. The quotient rule follows by combining the product rule with the derivative of a reciprocal.'},
 {id:'chain',title:'Pass a change through',verb:'Nudge → transform → transmit',intro:'One function feeds another. A small input change gets scaled once by the inside function, then again by the outside function.',defaults:{x:1,h:.2},controls:[slider('x','Input, x',-2,2,.05),slider('h','Input nudge, Δx',.01,.5,.01)],action:'Shrink the nudge',tip:'Move x below zero. The inside function then decreases as x increases, so the final response changes sign.',question:'For ln(1+x²), what happens to the derivative at x = 0?',answers:['It is zero','It is one','It is undefined'],correct:0,feedback:'The outside function is sensitive, but the inside sensitivity 2x is zero. Their product is zero; the finite change is still positive and second order.',formal:String.raw`u=1+x^2,\quad y=\ln u,\qquad \frac{dy}{dx}=\frac{dy}{du}\frac{du}{dx}=\frac{2x}{1+x^2}`,advanced:'For vector maps the same operation becomes Jacobian multiplication: D(g∘f)(x)=Dg(f(x))Df(x). Matrix order matters. Leibniz notation helps track the intermediate variable, but the chain rule is a composition of linear maps.'},
 {id:'logs',title:'Turn multiplication into distance',verb:'Multiply → measure → linearize',intro:'On a log ruler, equal ratios travel equal distances. The natural-log derivative 1/x is the conversion rate between an ordinary step and a log step.',defaults:{x:2,pct:20,base:Math.E},controls:[slider('x','Starting amount, x',.5,8,.1),slider('pct','Proportional change (%)',-80,100,1),choice('base','Logarithm base',[[String(Math.E),'e · natural log'],['10','10'],['2','2']])],action:'Halve the percentage',tip:'Compare 2 → 4 with 4 → 8. Both double, so both travel the same log distance. The approximation gets worse for large percentage changes.',question:'A 100% increase has which exact natural-log change?',answers:['1','ln 2 ≈ 0.693','2'],correct:1,feedback:'Doubling means x₁/x₀=2. Therefore Δln x=ln 2. The familiar “log change ≈ percentage change” is a small-change approximation.',formal:String.raw`\Delta\ln x=\ln\!\left(\frac{x+\Delta x}{x}\right)=\ln(1+r)\approx r,\quad \frac{d\log_b x}{dx}=\frac1{x\ln b}`,advanced:'Logs take dimensionless arguments: for a measured quantity X, use ln(X/Xref). The reference cancels in log differences. For positive f, d ln f/dx=f′/f; elasticity d ln f/d ln x=xf′/f. Changing the log base rescales both log axes and leaves an elasticity unchanged.'},
 {id:'partials',title:'Hold one input still',verb:'Freeze → slice → combine',intro:'Output depends on capital and labor. Move one input while holding the other fixed, then move both and compare their combined first-order effect.',defaults:{x:4,y:3,alpha:.4,dx:.4,dy:.2},controls:[slider('x','Capital, K',1,6,.1),slider('y','Labor, L',1,6,.1),slider('alpha','Capital exponent, α',.1,.9,.05),slider('dx','Capital move, ΔK',-.5,.5,.05),slider('dy','Labor move, ΔL',-.5,.5,.05)],action:'Halve both moves',tip:'Set ΔL to zero to isolate MPK. Then restore it: total change also depends on how labor moves.',question:'In Y = KᵅL¹⁻ᵅ, is α the marginal product of capital?',answers:['Yes, always','No: MPK is αY/K','Only if labor is fixed'],correct:1,feedback:'α is the capital elasticity: a local 1% increase in K raises Y by approximately α%. MPK is αY/K, measured in output per unit of capital.',formal:String.raw`Y=K^\alpha L^{1-\alpha},\quad Y_K=\alpha Y/K,\quad Y_L=(1-\alpha)Y/L,\quad dY=Y_K\,dK+Y_L\,dL`,advanced:'The partial derivative holds the other coordinate fixed. Along a path L=L(K), the total derivative is dY/dK=Y_K+Y_L L′(K). Equality KY_K+LY_L=Y follows from degree-one homogeneity. Units here are normalized; a production scale coefficient would carry the required units in a dimensional application.'},
 {id:'gradient',title:'Choose a direction',verb:'Turn → project → climb',intro:'Two partial derivatives make a gradient. A direction chooses how much of each to use. The directional derivative measures the slope along that direction.',defaults:{x:1,y:1,angle:45,shape:'bowl'},controls:[choice('shape','Landscape',[['bowl','Bowl · x²+y²'],['saddle','Saddle · x²−y²']]),slider('x','Horizontal location, x',-2,2,.1),slider('y','Vertical location, y',-2,2,.1),slider('angle','Direction angle (degrees)',0,360,5)],action:'Aim uphill',tip:'At the saddle’s center the gradient vanishes, yet one direction curves up and another curves down. Zero slope alone cannot classify a point.',question:'At a saddle point, does ∇f = 0 imply a minimum?',answers:['Yes','No','Only if the surface is smooth'],correct:1,feedback:'A smooth saddle can have zero gradient and opposite curvatures in different directions. Its Hessian has both positive and negative eigenvalues.',formal:String.raw`v=(\cos\theta,\sin\theta),\quad D_vf=\nabla f\cdot v,\quad D_v^2f=v^\top Hf\,v`,advanced:'For a differentiable function and a unit direction, Cauchy–Schwarz bounds the slope by ‖∇f‖. At nonstationary points the gradient is the steepest Euclidean ascent direction. This depends on the metric and coordinate scaling. Existence of all partial derivatives alone does not guarantee differentiability.'},
 {id:'taylor',title:'Watch an approximation break',verb:'Predict → bend → measure error',intro:'The tangent makes a linear prediction. Curvature adds a quadratic correction. Move farther away and watch the gap from the true curve.',defaults:{fn:'log',x:1,h:.5},controls:[choice('fn','Function',[['log','ln x'],['exp','eˣ'],['cube','x³']]),slider('x','Expansion point, x',.6,2,.05),slider('h','Distance from expansion point, Δx',-.5,1,.05)],action:'Halve the distance',tip:'Compare errors before and after halving Δx. The second-order approximation often improves much faster locally, but it is still local.',question:'Which term adds curvature to a tangent approximation?',answers:['f′(x)Δx','½f″(x)(Δx)²','f(x)²'],correct:1,feedback:'The quadratic term uses the second derivative. Its factor ½ makes the approximating polynomial have the correct second derivative at the expansion point.',formal:String.raw`f(x+h)\approx f(x)+f'(x)h+\tfrac12 f''(x)h^2`,advanced:'With three continuous derivatives near the interval, the quadratic remainder is f‴(ξ)h³/6 for some ξ between the endpoints. In several variables the correction is ½hᵀHf(x)h. Small floating-point or finite-difference residuals alone do not prove a mathematical limit.'},
 {id:'optimize',title:'Spend the next unit wisely',verb:'Compare marginal benefit and cost',intro:'An extra unit is worth adding while its marginal benefit exceeds marginal cost. Find where the two balance and check that curvature supports a maximum.',defaults:{x:2,c:3},controls:[slider('x','Quantity, q',.5,8,.1),slider('c','Marginal cost, c',1.5,8,.1)],action:'Move toward the optimum',tip:'Raise the marginal cost. The best quantity falls because the next unit must now clear a higher hurdle.',question:'When 12/q − c is negative, which small move raises payoff?',answers:['Increase q','Decrease q','Neither'],correct:1,feedback:'A negative derivative means moving right lowers payoff locally. Moving left raises it, provided q stays positive.',formal:String.raw`\pi(q)=12\ln q-cq,\quad \pi'(q)=12/q-c,\quad q^*=12/c,\quad \pi''(q)=-12/q^2<0`,advanced:'Strict concavity on q>0 makes the stationary point the unique global maximum here. With constraints, the solution may lie at a boundary and the derivative need not vanish. First-order conditions are candidates, not a universal certificate of optimality.'},
 {id:'integral',title:'Build a quantity from its rate',verb:'Accumulate → extend → differentiate',intro:'A derivative extracts a rate; an integral accumulates it. Extend the endpoint of an area and compare the new area with a thin rectangle.',defaults:{x:1.5,h:.4},controls:[slider('x','Endpoint, x',-2,2,.05),slider('h','Endpoint extension, Δx',.01,.8,.01)],action:'Thin the new strip',tip:'Move the endpoint below zero. The integral from 0 to x is negative because the orientation reverses, even though t² stays positive.',question:'If A(x) = ∫₀ˣ t² dt, what is A′(x)?',answers:['x²','2x','x³/3'],correct:0,feedback:'The extra area per unit endpoint motion approaches the height x². The fundamental theorem connects accumulation and differentiation.',formal:String.raw`A(x)=\int_0^x t^2\,dt=x^3/3,\quad A'(x)=x^2,\quad \Delta A\approx x^2\Delta x`,advanced:'Continuity of the integrand at x is sufficient for the fundamental theorem in this form. An integral is signed accumulation, not always geometric area. With a moving endpoint g(x), the chain rule gives d[∫₀^{g(x)} f(t)dt]/dx=f(g(x))g′(x).'}
];
export const byId=Object.fromEntries(lessons.map(l=>[l.id,l]));
export function curve(fn,x){switch(fn){case 'square':return {value:x*x,slope:2*x,curvature:2};case 'cube':return {value:x**3,slope:3*x*x,curvature:6*x};case 'sin':return {value:Math.sin(x),slope:Math.cos(x),curvature:-Math.sin(x)};case 'exp':return {value:Math.exp(x),slope:Math.exp(x),curvature:Math.exp(x)};case 'abs':return {value:Math.abs(x),slope:x===0?null:Math.sign(x),curvature:x===0?null:0};case 'log':if(x<=0)throw new RangeError('Logarithms require a positive input.');return {value:Math.log(x),slope:1/x,curvature:-1/x**2};default:throw new RangeError('Unknown function.');}}
export function calculate(id,p){
 if(!byId[id])throw new RangeError('Unknown lesson.');
 for(const v of Object.values(p))if(typeof v==='number'&&!Number.isFinite(v))throw new RangeError('Inputs must be finite.');
 const {x,h}=p;let r;
 if(id==='slope'){if(!(h>0))throw new RangeError('The finite move must be positive.');const a=curve(p.fn,x),b=curve(p.fn,x+h);r={...a,end:b.value,actual:b.value-a.value,linear:a.slope===null?null:a.slope*h,secant:(b.value-a.value)/h,left:(a.value-curve(p.fn,x-h).value)/h};}
 if(id==='product'){if(!(x>0&&h>0))throw new RangeError('Rectangle lengths must be positive.');r={value:x*(x+1),slope:2*x+1,first:(x+1)*h,second:x*h,corner:h*h,actual:(2*x+1)*h+h*h,linear:(2*x+1)*h};}
 if(id==='chain'){const inner=1+x*x,slope=2*x/inner;r={inner,innerSlope:2*x,outerSlope:1/inner,slope,value:Math.log(inner),innerChange:2*x*h+h*h,actual:Math.log1p((2*x*h+h*h)/inner),linear:slope*h};}
 if(id==='logs'){const {pct,base}=p;if(!(x>0&&pct>-100&&base>0&&base!==1))throw new RangeError('Logs need x > 0, a positive endpoint, and a positive base other than 1.');r={value:Math.log(x)/Math.log(base),end:x*(1+pct/100),slope:1/(x*Math.log(base)),actual:Math.log1p(pct/100)/Math.log(base),linear:pct/100/Math.log(base),ratio:1+pct/100};}
 if(id==='partials'){const {y,alpha,dx,dy}=p;if(!(x>0&&y>0&&x+dx>0&&y+dy>0&&alpha>0&&alpha<1))throw new RangeError('Production inputs must stay positive and 0 < α < 1.');const value=x**alpha*y**(1-alpha),fx=alpha*value/x,fy=(1-alpha)*value/y;r={value,fx,fy,elasticity:alpha,kPart:fx*dx,lPart:fy*dy,linear:fx*dx+fy*dy,actual:(x+dx)**alpha*(y+dy)**(1-alpha)-value};}
 if(id==='gradient'){const {y,angle,shape}=p;if(!['bowl','saddle'].includes(shape))throw new RangeError('Unknown landscape.');const sign=shape==='bowl'?1:-1,vx=Math.cos(angle*Math.PI/180),vy=Math.sin(angle*Math.PI/180);r={value:x*x+sign*y*y,fx:2*x,fy:2*sign*y,vx,vy,directional:2*x*vx+2*sign*y*vy,curvature:2*vx*vx+2*sign*vy*vy,norm:2*Math.hypot(x,y)};}
 if(id==='taylor'){const a=curve(p.fn,x),end=curve(p.fn,x+h).value;r={...a,end,linear:a.value+a.slope*h,quadratic:a.value+a.slope*h+.5*a.curvature*h*h,error1:end-a.value-a.slope*h,error2:end-a.value-a.slope*h-.5*a.curvature*h*h,actual:end-a.value};}
 if(id==='optimize'){if(!(x>0&&p.c>0))throw new RangeError('Quantity and cost must be positive.');const optimum=12/p.c,value=12*Math.log(x)-p.c*x;r={value,slope:12/x-p.c,curvature:-12/x**2,optimum,gain:12*Math.log(optimum)-p.c*optimum-value};}
 if(id==='integral'){r={value:x**3/3,slope:x*x,actual:x*x*h+x*h*h+h**3/3,linear:x*x*h};}
 for(const v of Object.values(r))if(typeof v==='number'&&!Number.isFinite(v))throw new RangeError('The calculation exceeded its numerical domain.');return r;
}
