import katex from 'katex';
import {productScene,surfaceScene,patchScene} from './calculus-scenes.mjs';
import {lessons,byId,calculate,curve} from '../lib/calculus.mjs';
const f=n=>n===null?'does not exist':new Intl.NumberFormat('en-US',{maximumFractionDigits:5}).format(Math.abs(n)<1e-12?0:n);
const tick=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Math.abs(n)<1e-10?0:n);
const tex=(s,display=true)=>katex.renderToString(s,{displayMode:display,throwOnError:true,output:'htmlAndMathml'});
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const samples=(a,b,fn,n=100)=>Array.from({length:n+1},(_,i)=>{const x=a+(b-a)*i/n;return [x,fn(x)];});
const line=(a,b,color='blue',dash=false)=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" class="cl-${color}" ${dash?'stroke-dasharray="7 5"':''}/>`;
const text=(x,y,s,cls='')=>`<text x="${x}" y="${y}" class="${cls}">${escape(s)}</text>`;
function probe(x,y,color='blue'){return `<g transform="translate(${x},${y})"><circle r="8" class="cl-probe cl-fill-${color}"/><circle cx="-2.5" cy="-1.5" r="1.2" fill="white"/><circle cx="2.5" cy="-1.5" r="1.2" fill="white"/></g>`;}
function chart({series,points=[],xRange,yRange,xLabel='x',yLabel='output',shade,extra='',interactive=true,p,caption}){
 const [xmin,xmax]=xRange,all=series.flatMap(s=>s.points.map(v=>v[1])).filter(Number.isFinite);let [ymin,ymax]=yRange??[Math.min(...all),Math.max(...all)];const pad=(ymax-ymin||1)*.12;if(!yRange){ymin-=pad;ymax+=pad;}const X=x=>60+480*(x-xmin)/(xmax-xmin),Y=y=>294-254*(y-ymin)/(ymax-ymin);let svg='';
 for(let i=0;i<=4;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;svg+=line([X(x),40],[X(x),294],'grid')+line([60,Y(y)],[540,Y(y)],'grid')+text(X(x),316,tick(x),'cl-tick cl-center')+text(50,Y(y)+4,tick(y),'cl-tick cl-end');}
 const path=points=>points.map((v,i)=>`${i?'L':'M'}${X(v[0])},${Y(v[1])}`).join(' ');
 if(shade?.length)svg+=`<path d="${path(shade)} Z" class="cl-area"/>`;
 svg+=`<g clip-path="url(#cl-plot-clip)">`;
 for(const s of series)svg+=`<path d="${path(s.points)}" class="cl-${s.color??'blue'}" fill="none" ${s.dash?'stroke-dasharray="6 5"':''}/>`;
 for(const v of points)svg+=probe(X(v.x),Y(v.y),v.color);svg+='</g>'+extra;
 const label=interactive?`tabindex="0" role="slider" aria-label="${escape(caption)}. Move x with arrow keys or drag the probe." aria-valuemin="${xmin}" aria-valuemax="${xmax}" aria-valuenow="${p.x}" data-coordinate-plot data-xmin="${xmin}" data-xmax="${xmax}"`: `role="img" aria-label="${escape(caption)}"`;
 return `<svg viewBox="0 0 580 352" ${label}><defs><clipPath id="cl-plot-clip"><rect x="60" y="40" width="480" height="254"/></clipPath></defs>${svg}${text(300,344,xLabel,'cl-center')}${text(60,23,yLabel)}</svg><div class="cl-legend">${series.map(s=>`<span><i class="cl-bg-${s.color??'blue'}"></i>${escape(s.label)}</span>`).join('')}</div>`;
}
function visual(id,p,r,view={}){
 if(id==='product')return productScene(p,view.split??0);
 if(['partials','gradient'].includes(id)&&view.surface)return surfaceScene(id,p,r,view.yaw);
 if(id==='logs'){
  const xmin=.08,xmax=16.1,L=Math.log(p.base),X=x=>60+x/xmax*480,Z=x=>60+(Math.log(x)-Math.log(xmin))/(Math.log(xmax)-Math.log(xmin))*480;let s=line([60,100],[540,100],'grid')+line([60,240],[540,240],'grid');
  for(const x of [.125,.25,.5,1,2,4,8,16])s+=line([X(x),96],[X(x),104],'ink')+line([Z(x),235],[Z(x),245],'ink')+text(Z(x),269,String(x),'cl-center cl-tick');
  for(const x of [0,4,8,12,16])s+=text(X(x),129,String(x),'cl-center cl-tick');
  s+=line([X(p.x),100],[Z(p.x),240],'blue',true)+line([X(r.end),100],[Z(r.end),240],'orange',true)+probe(X(p.x),100)+probe(X(r.end),100,'orange')+probe(Z(p.x),240)+probe(Z(r.end),240,'orange');
  return `<svg viewBox="0 0 580 340" role="img" aria-label="Linear and logarithmic rulers connect the same starting and ending amounts">${text(60,45,'Ordinary ruler · equal differences')}${text(60,195,'Log ruler · equal ratios')}${s}${text(60,318,`Log coordinates: ${f(Math.log(p.x)/L)} → ${f(Math.log(r.end)/L)}`)}</svg><div class="cl-legend"><span><i class="cl-bg-blue"></i>Start ${f(p.x)}</span><span><i class="cl-bg-orange"></i>End ${f(r.end)} · ×${f(r.ratio)}</span></div>`;
 }
 if(id==='partials'||id==='gradient'){
  const production=id==='partials',lo=production?.5:-3,hi=production?6.5:3,X=x=>60+(x-lo)/(hi-lo)*480,Y=y=>294-(y-lo)/(hi-lo)*254,fun=(x,y)=>production?x**p.alpha*y**(1-p.alpha):x*x+(p.shape==='bowl'?1:-1)*y*y;let s='';const n=24;
  for(let i=0;i<n;i++)for(let j=0;j<n;j++){const x=lo+(hi-lo)*(i+.5)/n,y=lo+(hi-lo)*(j+.5)/n,val=fun(x,y),scaled=production?val/7:(val+6.25)/18.75;s+=`<rect x="${60+i*480/n}" y="${40+(n-1-j)*254/n}" width="20.2" height="10.8" fill="hsl(228 65% ${96-45*Math.max(0,Math.min(1,scaled))}%)"/>`;}
  // Analytic level sets, in the same coordinates as the colored surface.
  for(const level of production?[1,2,3,4,5,6]:p.shape==='bowl'?[.5,1,2,4,6]:[-4,-2,-.5,.5,2,4]){
   let branches=[];if(production)branches=[samples(lo,hi,x=>(level/x**p.alpha)**(1/(1-p.alpha)))];else if(p.shape==='bowl')branches=[Array.from({length:101},(_,i)=>{const a=i/100*2*Math.PI;return [Math.sqrt(level)*Math.cos(a),Math.sqrt(level)*Math.sin(a)];})];else for(const sign of [-1,1])branches.push(samples(lo,hi,x=>sign*Math.sqrt(x*x-level)));
   for(const b of branches){let pen=false,d='';for(const [x,y]of b){if(!Number.isFinite(y)||y<lo||y>hi){pen=false;continue;}d+=`${pen?'L':'M'}${X(x)},${Y(y)} `;pen=true;}s+=`<path d="${d}" fill="none" stroke="#334b89" stroke-opacity=".45" stroke-width="1"/>`;}
  }
  if(production){s+=line([60,Y(p.y)],[540,Y(p.y)],'teal',true)+line([X(p.x),40],[X(p.x),294],'orange',true)+line([X(p.x),Y(p.y)],[X(p.x+p.dx),Y(p.y+p.dy)],'ink')+probe(X(p.x+p.dx),Y(p.y+p.dy),'orange');}
  else {const norm=r.norm||1;s+=line([X(p.x),Y(p.y)],[X(p.x+.7*r.fx/norm),Y(p.y+.7*r.fy/norm)],'teal')+line([X(p.x),Y(p.y)],[X(p.x+.7*r.vx),Y(p.y+.7*r.vy)],'orange')+probe(X(p.x+.7*r.vx),Y(p.y+.7*r.vy),'orange');}
  s+=probe(X(p.x),Y(p.y));for(let i=0;i<=4;i++){const z=lo+(hi-lo)*i/4;s+=text(X(z),315,f(z),'cl-center cl-tick')+text(49,Y(z)+4,f(z),'cl-end cl-tick');}
  const main=`<svg viewBox="0 0 580 352" tabindex="0" role="slider" aria-label="${production?'Production map':'Landscape map'}. Arrow keys move horizontally; drag to move both coordinates." aria-valuemin="${lo}" aria-valuemax="${hi}" aria-valuenow="${p.x}" data-coordinate-plot data-xy data-xmin="${lo}" data-xmax="${hi}" data-ymin="${lo}" data-ymax="${hi}">${s}${text(60,24,production?'Labor, L · darker means more output':'y · darker means a higher function value')}${text(300,344,production?'Capital, K':'x','cl-center')}</svg>`;
  const slice=production?samples(.5,6.5,x=>fun(x,p.y)):samples(-.5,.5,t=>fun(p.x+t*r.vx,p.y+t*r.vy));
  return main+`<div class="cl-legend"><span><i class="cl-bg-blue"></i>Current point</span><span><i class="cl-bg-orange"></i>${production?'New point / fixed K':'Chosen direction'}</span><span><i class="cl-bg-teal"></i>${production?'Fixed L':'Gradient direction'}</span></div><h4>${production?'Slice: change capital, hold labor still':'Slice along your chosen direction'}</h4>`+chart({series:[{label:production?'Y(K, fixed L)':'f(point + tv)',points:slice},{label:'Local linear prediction',color:'orange',dash:true,points:production?samples(.5,6.5,x=>r.value+r.fx*(x-p.x)):samples(-.5,.5,t=>r.value+r.directional*t)}],xRange:production?[.5,6.5]:[-.5,.5],xLabel:production?'Capital, K':'Distance t in the chosen unit direction',yLabel:'Function value',interactive:false,p,caption:'One-dimensional slice and its tangent'});
 }
 let fn,xmin,xmax,series=[],points=[],shade;
 if(id==='slope'){fn=x=>curve(p.fn,x).value;xmin=-2.5;xmax=3;series=[{label:'Function',points:samples(xmin,xmax,fn)},{label:'Secant · finite move',color:'orange',points:samples(p.x-.5,p.x+p.h+.5,x=>r.value+r.secant*(x-p.x))}];if(r.slope!==null)series.push({label:'Tangent · derivative',color:'teal',dash:true,points:samples(p.x-.7,p.x+.7,x=>r.value+r.slope*(x-p.x))});points=[{x:p.x,y:r.value},{x:p.x+p.h,y:fn(p.x+p.h),color:'orange'}];}
 if(id==='chain'){fn=x=>Math.log1p(x*x);xmin=-2.5;xmax=2.5;series=[{label:'Composed function ln(1+x²)',points:samples(xmin,xmax,fn)},{label:'Local linear prediction',color:'orange',dash:true,points:samples(p.x-.5,p.x+.5,x=>r.value+r.slope*(x-p.x))}];points=[{x:p.x,y:r.value},{x:p.x+p.h,y:fn(p.x+p.h),color:'orange'}];}
 if(id==='taylor'){fn=x=>curve(p.fn,x).value;xmin=.1;xmax=3;series=[{label:'True function',points:samples(xmin,xmax,fn)},{label:'Linear',color:'teal',dash:true,points:samples(xmin,xmax,x=>r.value+r.slope*(x-p.x))},{label:'Quadratic',color:'orange',dash:true,points:samples(xmin,xmax,x=>r.value+r.slope*(x-p.x)+.5*r.curvature*(x-p.x)**2)}];points=[{x:p.x,y:r.value},{x:p.x+p.h,y:r.end,color:'orange'}];}
 if(id==='optimize'){fn=x=>12*Math.log(x)-p.c*x;xmin=.3;xmax=8.5;series=[{label:'Payoff',points:samples(xmin,xmax,fn)},{label:'Marginal direction at q',color:'orange',points:samples(Math.max(.3,p.x-.7),p.x+.7,x=>r.value+r.slope*(x-p.x))}];points=[{x:p.x,y:r.value},{x:r.optimum,y:fn(r.optimum),color:'teal'}];}
 if(id==='integral'){fn=x=>x*x;xmin=-2.5;xmax=3;series=[{label:'Rate f(t) = t²',points:samples(xmin,xmax,fn)}];points=[{x:p.x,y:fn(p.x)},{x:p.x+p.h,y:fn(p.x+p.h),color:'orange'}];shade=[[0,0],...samples(0,p.x,fn),[p.x,0]];}
 let before='';if(id==='chain')before=`<div class="cl-chain"><div><small>Input</small><strong>x = ${f(p.x)}</strong><span>Δx = ${f(p.h)}</span></div><b>→</b><div><small>Square, then add 1</small><strong>u = ${f(r.inner)}</strong><span>× ${f(r.innerSlope)} locally</span></div><b>→</b><div><small>Take the log</small><strong>y = ${f(r.value)}</strong><span>× ${f(r.outerSlope)} locally</span></div></div>`;
 return before+chart({series,points,xRange:[xmin,xmax],shade,p,xLabel:id==='optimize'?'Quantity, q':id==='integral'?'Integration coordinate, t':'Input, x',yLabel:id==='integral'?'Rate t²':id==='optimize'?'Payoff π(q)':'Function value',caption:byId[id].title});
}
function readings(id,p,r){
 const metric=(label,n)=>[label,typeof n==='string'?n:f(n)];
 if(id==='slope')return [metric('Derivative at x',r.slope),metric('Finite right slope',r.secant),metric('Finite left slope',r.left)];
 if(id==='product')return [metric('Exact area added',r.actual),metric('Strip prediction',r.linear),metric('Corner left over',r.corner)];
 if(id==='chain')return [metric('Combined derivative',r.slope),metric('Exact output change',r.actual),metric('Linear prediction',r.linear)];
 if(id==='logs')return [metric('Exact log change',r.actual),metric('Linear prediction',r.linear),metric('Derivative at start',r.slope)];
 if(id==='partials')return [metric('MPK · ∂Y/∂K',r.fx),metric('MPL · ∂Y/∂L',r.fy),metric('Capital elasticity',r.elasticity)];
 if(id==='gradient')return [metric('Slope in chosen direction',r.directional),metric('Greatest unit-direction slope',r.norm),metric('Curvature in this direction',r.curvature)];
 if(id==='taylor')return [metric('True endpoint value',r.end),metric('Linear error · true − prediction',r.error1),metric('Quadratic error',r.error2)];
 if(id==='optimize')return [metric('Marginal net benefit',r.slope),metric('Best quantity q*',r.optimum),metric('Gain from moving to q*',r.gain)];
 return [metric('Signed accumulation A(x)',r.value),metric('Exact additional accumulation',r.actual),metric('Thin-strip prediction',r.linear)];
}
function substitution(id,p,r){const n=x=>Math.abs(x)<1e-10?'0':Number(x.toPrecision(6)).toString();
 if(id==='slope')return r.slope===null?String.raw`f'(${n(p.x)})\text{ does not exist: the one-sided slopes disagree.}`:String.raw`x=${n(p.x)},\quad \Delta x=${n(p.h)},\quad f'(x)=${n(r.slope)},\quad \frac{\Delta f}{\Delta x}\approx${n(r.secant)}`;
 if(id==='product')return String.raw`\Delta A=${n(r.first)}+${n(r.second)}+${n(r.corner)}=${n(r.actual)}`;
 if(id==='chain')return String.raw`\frac{dy}{dx}=${n(r.outerSlope)}\times(${n(r.innerSlope)})\approx${n(r.slope)}`;
 if(id==='logs')return String.raw`\Delta\log_b x=\log_b(${n(r.ratio)})\approx${n(r.actual)},\quad d\log_b x\approx${n(r.linear)}`;
 if(id==='partials')return String.raw`dY\approx${n(r.fx)}(${n(p.dx)})+${n(r.fy)}(${n(p.dy)})=${n(r.linear)},\quad \Delta Y\approx${n(r.actual)}`;
 if(id==='gradient')return String.raw`D_vf=(${n(r.fx)},${n(r.fy)})\cdot(${n(r.vx)},${n(r.vy)})\approx${n(r.directional)}`;
 if(id==='taylor')return String.raw`f(x+h)\approx${n(r.end)},\quad T_1=${n(r.linear)},\quad T_2=${n(r.quadratic)}`;
 if(id==='optimize')return String.raw`\pi'(${n(p.x)})=\frac{12}{${n(p.x)}}-${n(p.c)}\approx${n(r.slope)},\quad q^*=\frac{12}{${n(p.c)}}=${n(r.optimum)}`;
 return String.raw`\Delta A\approx${n(r.actual)},\qquad A'(x)\Delta x=(${n(p.x)})^2(${n(p.h)})=${n(r.linear)}`;
}
export function initializeCalculus(doc){
 const root=doc.querySelector('[data-calculus]');if(!root||root.dataset.ready)return;root.dataset.ready='true';const win=doc.defaultView;
 const first=byId[win.location.hash.slice(1)]?win.location.hash.slice(1):'slope';const state={lesson:first,params:{...byId[first].defaults},result:null,view:{split:0,surface:false,yaw:-.7},focused:false};let frame=null,dragging=false,dragStart=null;
 root.innerHTML=`<label class="cl-picker">Experiment <select data-lesson-select>${lessons.map((l,i)=>`<option value="${l.id}">${i+1}. ${escape(l.title)}</option>`).join('')}</select></label><nav class="cl-chapters" aria-label="Calculus experiments">${lessons.map((l,i)=>`<button type="button" data-lesson="${l.id}"><span>${String(i+1).padStart(2,'0')}</span>${l.title}</button>`).join('')}</nav><div class="cl-workspace"><header class="cl-lesson-heading"><p class="cl-eyebrow" data-verb></p><h2 data-title></h2><p data-intro></p></header><div class="cl-experiment"><div class="cl-stage"><div class="cl-stage-toolbar"><div class="cl-scene-switches"><button type="button" data-split aria-pressed="false" hidden>Separate pieces</button><button type="button" data-surface aria-pressed="false" hidden>Surface ↗</button><span data-scene-label>Direct manipulation</span></div><div class="cl-transport"><button type="button" data-animate aria-pressed="false">Play ↗</button><button type="button" data-focus aria-pressed="false">Focus ⤢</button></div></div><div data-visual></div><label class="cl-camera" hidden>Orbit <input type="range" data-camera min="-180" max="180" step="1" value="-40" aria-label="Surface camera angle"/></label><p class="cl-gesture" data-gesture>Drag on the graph, use arrow keys, or adjust the controls.</p></div><aside class="cl-controls"><div class="cl-control-title"><h3>Try it</h3><button type="button" data-reset>Reset</button></div><div data-controls></div><button type="button" data-action></button><p data-tip></p></aside></div><p data-error role="alert" hidden></p><div class="cl-readout" data-readout aria-live="polite"></div><section class="cl-math"><div><p class="cl-eyebrow">The same move, in symbols</p><div data-formula></div></div><div data-live-math></div><p>Δ denotes a finite change; d denotes the local linear prediction. Displayed numbers are rounded. Coordinates are dimensionless or normalized.</p></section><div class="cl-learning"><section class="cl-challenge"><p class="cl-eyebrow">Make a prediction</p><h3 data-question></h3><div data-answers></div><p data-feedback aria-live="polite">Choose an answer to test your reasoning.</p></section><section class="cl-depth"><details><summary>Go deeper: definitions &amp; limits</summary><p data-advanced></p></details><p data-bridge></p><button type="button" data-next>Next experiment →</button></section></div></div>`;
 const $=s=>root.querySelector(s);
 $('.cl-experiment').prepend($('.cl-lesson-heading'));$('.cl-experiment').append($('[data-readout]'));
 const short=['Slope','Product','Chain','Logs','Partials','Gradient','Taylor','Optimum','Integral'];root.querySelectorAll('[data-lesson]').forEach((b,i)=>{b.setAttribute('aria-label',`${i+1}. ${lessons[i].title}`);b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><span class="cl-nav-label">${short[i]}</span>`;});
 function stop(){if(frame!==null)win.cancelAnimationFrame(frame);frame=null;$('[data-animate]').textContent='Play ↗';$('[data-animate]').setAttribute('aria-pressed','false');}
 function controls(){const l=byId[state.lesson];$('[data-controls]').innerHTML=l.controls.map(c=>c.options?`<label class="cl-control">${escape(c.label)}<select data-control="${c.key}">${c.options.map(([v,t])=>`<option value="${v}" ${String(state.params[c.key])===v?'selected':''}>${escape(t)}</option>`).join('')}</select></label>`:`<label class="cl-control"><span>${escape(c.label)} <output data-output="${c.key}">${f(state.params[c.key])}</output></span><input type="range" data-control="${c.key}" min="${c.min}" max="${c.max}" step="${c.step}" value="${state.params[c.key]}" /></label>`).join('');}
 function render(){const l=byId[state.lesson];try{state.result=calculate(state.lesson,state.params);$('[data-error]').hidden=true;}catch(e){$('[data-error]').textContent=e.message;$('[data-error]').hidden=false;stop();return;}
  const focus=doc.activeElement?.hasAttribute('data-coordinate-plot');patchScene($('[data-visual]'),visual(state.lesson,state.params,state.result,state.view));const plot=$('[data-coordinate-plot]'),xControl=l.controls.find(c=>c.key==='x');if(plot){plot.setAttribute('aria-valuemin',xControl.min);plot.setAttribute('aria-valuemax',xControl.max);}if(focus)plot?.focus();
  $('[data-readout]').innerHTML=readings(state.lesson,state.params,state.result).map(([k,v])=>`<div><span>${escape(k)}</span><strong>${escape(v)}</strong></div>`).join('');$('[data-live-math]').innerHTML=tex(substitution(state.lesson,state.params,state.result));
  for(const c of l.controls){const input=$(`[data-control="${c.key}"]`);input.value=state.params[c.key];const out=$(`[data-output="${c.key}"]`);if(out)out.textContent=f(state.params[c.key]);}
 }
 function setLesson(id,hash=true){if(!byId[id])return;stop();state.lesson=id;state.view={split:0,surface:false,yaw:-.7};state.params={...byId[id].defaults};const l=byId[id],index=lessons.indexOf(l);$('[data-lesson-select]').value=id;root.querySelectorAll('[data-lesson]').forEach(b=>b.setAttribute('aria-current',b.dataset.lesson===id?'step':'false'));$('[data-verb]').textContent=l.verb;$('[data-title]').textContent=l.title;$('[data-intro]').textContent=l.intro;$('[data-tip]').textContent=l.tip;$('[data-action]').textContent=l.action;$('[data-formula]').innerHTML=tex(l.formal);$('[data-question]').textContent=l.question;$('[data-answers]').innerHTML=l.answers.map((a,i)=>`<button type="button" data-answer="${i}">${escape(a)}</button>`).join('');$('[data-feedback]').textContent='Choose an answer to test your reasoning.';$('[data-advanced]').textContent=l.advanced;$('[data-bridge]').innerHTML=id==='partials'||id==='optimize'?'<a href="/macroeconomics/">Use these ideas in the macroeconomics suite ↗</a>':'Keep the question in mind: which inputs change, and which stay fixed?';$('[data-next]').textContent=index===lessons.length-1?'Back to the first experiment ↺':`Next: ${lessons[index+1].title} →`;$('[data-gesture]').textContent=id==='product'?'Drag the gold corner, use its arrow keys, or separate the pieces.':id==='logs'?'Change the controls to transform the picture.':'Drag on the graph, use arrow keys, or adjust the controls.';if(hash)win.history.replaceState(null,'',`#${id}`);controls();$('[data-split]').hidden=id!=='product';$('[data-split]').setAttribute('aria-pressed','false');$('[data-split]').textContent='Separate pieces';$('[data-surface]').hidden=!['partials','gradient'].includes(id);$('[data-surface]').setAttribute('aria-pressed','false');$('[data-surface]').textContent='Surface ↗';$('.cl-camera').hidden=true;render();if(!win.matchMedia?.('(prefers-reduced-motion: reduce)').matches)$('.cl-experiment').animate?.([{opacity:.55,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'cubic-bezier(.2,.75,.2,1)'});}
 function change(key,value,smooth=false){const c=byId[state.lesson].controls.find(c=>c.key===key);if(!c)return;if(!c.options)value=Math.max(c.min,Math.min(c.max,smooth?value:Math.round(value/c.step)*c.step));state.params[key]=value;render();}
 root.addEventListener('input',e=>{if(e.target.matches('[data-camera]')){state.view.yaw=Number(e.target.value)*Math.PI/180;render();}if(e.target.matches('input[data-control]')){stop();change(e.target.dataset.control,Number(e.target.value));}});
 root.addEventListener('change',e=>{if(e.target.matches('[data-lesson-select]'))setLesson(e.target.value);if(e.target.matches('select[data-control]')){stop();change(e.target.dataset.control,e.target.dataset.control==='base'?Number(e.target.value):e.target.value);}});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-split')){stop();state.view.split=1-state.view.split;b.setAttribute('aria-pressed',String(!!state.view.split));b.textContent=state.view.split?'Rejoin pieces':'Separate pieces';render();}if(b.hasAttribute('data-surface')){state.view.surface=!state.view.surface;b.setAttribute('aria-pressed',String(state.view.surface));b.textContent=state.view.surface?'Map ↙':'Surface ↗';$('.cl-camera').hidden=!state.view.surface;render();}if(b.hasAttribute('data-focus')){state.focused=!state.focused;root.classList.toggle('is-focused',state.focused);b.setAttribute('aria-pressed',String(state.focused));b.textContent=state.focused?'Exit focus ↙':'Focus ⤢';if(state.focused)$('.cl-experiment').scrollIntoView?.({block:'start',behavior:win.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}if(b.dataset.lesson)setLesson(b.dataset.lesson);if(b.hasAttribute('data-reset'))setLesson(state.lesson);if(b.hasAttribute('data-next'))setLesson(lessons[(lessons.findIndex(l=>l.id===state.lesson)+1)%lessons.length].id);if(b.dataset.answer!==undefined){const l=byId[state.lesson];$('[data-feedback]').textContent=(Number(b.dataset.answer)===l.correct?'Correct. ':'Not quite. ')+l.feedback;root.querySelectorAll('[data-answer]').forEach(a=>a.setAttribute('aria-pressed',String(a===b)));}
  if(b.hasAttribute('data-action')){stop();const p=state.params;if(state.lesson==='partials'){change('dx',p.dx/2);change('dy',p.dy/2);}else if(state.lesson==='gradient')change('angle',(Math.atan2(state.result.fy,state.result.fx)*180/Math.PI+360)%360);else if(state.lesson==='optimize')change('x',state.result.optimum);else if(state.lesson==='logs')change('pct',p.pct/2);else change('h',p.h/2);}
  if(b.hasAttribute('data-animate')){if(frame!==null){stop();return;}if(win.matchMedia?.('(prefers-reduced-motion: reduce)').matches){$('[data-gesture]').textContent='Reduced motion is enabled. Use the x slider or arrow keys to step through the experiment.';return;}b.textContent='Pause';b.setAttribute('aria-pressed','true');const c=byId[state.lesson].controls.find(c=>c.key==='x'),start=state.params.x;let t0;const tick=t=>{if(t0===undefined)t0=t;const progress=Math.min(1,(t-t0)/6000);const phase=((start-c.min)/(c.max-c.min)+2*progress)%2;change('x',c.min+(c.max-c.min)*(phase<=1?phase:2-phase),true);if(progress<1)frame=win.requestAnimationFrame(tick);else stop();};frame=win.requestAnimationFrame(tick);}
 });
 root.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.focused){$('[data-focus]').click();return;}if(e.target.closest('[data-growth-handle]')&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();stop();change('h',e.key==='Home'?.01:e.key==='End'?1:state.params.h+(['ArrowRight','ArrowUp'].includes(e.key)?.01:-.01));return;}if(e.target.matches('[data-surface-plot]')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();state.view.yaw+=(e.key==='ArrowRight'?1:-1)*.08;$('[data-camera]').value=state.view.yaw*180/Math.PI;render();return;}if(!e.target.matches('[data-coordinate-plot]'))return;const c=byId[state.lesson].controls.find(c=>c.key==='x');if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();stop();change('x',e.key==='Home'?c.min:e.key==='End'?c.max:state.params.x+(e.key==='ArrowRight'?1:-1)*c.step);}});
 function point(e){if(dragging==='growth'){const svg=$('[data-growth-handle]').ownerSVGElement,box=svg.getBoundingClientRect();const delta=((e.clientX-dragStart.x)/box.width*580+(e.clientY-dragStart.y)/box.height*390)/120;change('h',dragStart.h+delta);return;}if(dragging==='orbit'){state.view.yaw=dragStart.yaw+(e.clientX-dragStart.x)/160;$('[data-camera]').value=((state.view.yaw*180/Math.PI+180)%360+360)%360-180;render();return;}const svg=$('[data-coordinate-plot]');if(!svg)return;const box=svg.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*580,y=(e.clientY-box.top)/box.height*352;change('x',Number(svg.dataset.xmin)+(x-60)/480*(Number(svg.dataset.xmax)-Number(svg.dataset.xmin)));if(svg.hasAttribute('data-xy'))change('y',Number(svg.dataset.ymax)-(y-40)/254*(Number(svg.dataset.ymax)-Number(svg.dataset.ymin)));}
 root.addEventListener('pointerdown',e=>{if(e.target.closest('[data-coordinate-plot], [data-growth-handle], [data-surface-plot]')){stop();dragging=e.target.closest('[data-growth-handle]')?'growth':e.target.closest('[data-surface-plot]')?'orbit':'point';dragStart={x:e.clientX,y:e.clientY,h:state.params.h,yaw:state.view.yaw};root.setPointerCapture?.(e.pointerId);point(e);}});root.addEventListener('pointermove',e=>{if(dragging)point(e);});root.addEventListener('pointerup',()=>{dragging=false;});root.addEventListener('pointercancel',()=>{dragging=false;});win.addEventListener('hashchange',()=>setLesson(win.location.hash.slice(1),false));doc.addEventListener('visibilitychange',()=>{if(doc.hidden)stop();});setLesson(first,false);return {state,setLesson,stop};
}
if(typeof document!=='undefined')initializeCalculus(document);
