"""Reproduce the browser's 10 C, atmospheric-pressure TEOS-10 density table.

Run with: uv run --no-project --with gsw python scripts/hidden-rivers/build-tank-seawater.py
"""
import json
from pathlib import Path
import gsw
import numpy as np

root = Path(__file__).resolve().parents[2]
salinity = np.linspace(0, 40, 401)
rho = gsw.rho_t_exact(salinity, 10, 0)
check_s = np.linspace(0, 40, 16001)
error = float(np.max(np.abs(np.interp(check_s, salinity, rho) - gsw.rho_t_exact(check_s, 10, 0))))
assert error < .0005, error
metadata = {"gswVersion": gsw.__version__, "equation": "gsw.rho_t_exact(SA, 10, 0)", "temperatureC": 10, "seaPressureDbar": 0, "salinityUnits": "Absolute Salinity, g/kg", "densityUnits": "kg/m3", "stepGKg": .1, "maxInterpolationErrorKgM3": error, "reference": "https://www.teos-10.org/pubs/gsw/html/gsw_rho_t_exact.html"}
module = "// Generated by build-tank-seawater.py. TEOS-10; standard-composition water.\n"
module += "export const seawaterMetadata=" + json.dumps(metadata, separators=(",", ":")) + ";\n"
module += "const rho=" + json.dumps(np.round(rho, 10).tolist(), separators=(",", ":")) + ";\n"
module += """export function seawaterDensity(salinity){
 if(!Number.isFinite(salinity)||salinity<0||salinity>40)throw new RangeError('Density salinity must be 0–40 g/kg');
 const x=salinity*10,i=Math.min(399,Math.floor(x));return rho[i]+(rho[i+1]-rho[i])*(x-i);
}
export const referenceDensity=seawaterDensity(30);
"""
(root / "src/scripts/hidden-rivers/tank-seawater.mjs").write_text(module)
(root / "public/hidden-rivers/dye-tank/seawater.json").write_text(json.dumps({**metadata, "density": np.round(rho, 10).tolist()}, separators=(",", ":")) + "\n")
print(json.dumps(metadata))
