export const WATER_STORIES=[
 {id:'classroom',title:'How moving water supports life',subtitle:'Grades 4–8 · saltwater, melting ice and a connected ocean',thumb:'ocean',steps:[
  {place:'global',layer:'currents',title:'The ocean carries what life needs',text:'Ocean water moves between places, carrying heat, dissolved oxygen and nutrients. Animals need oxygen; tiny ocean plants need nutrients and sunlight. These lines show broad currents near the surface. Where might the water go next?',key:'Near-surface currents · NOAA drifter climatology · oxygen and nutrients are not mapped',source:'https://oceanexplorer.noaa.gov/ocean-fact/currents/'},
  {place:'denmark',layer:'currents',depth:1000,title:'Why does salty water sink?',text:'Put a little dyed saltwater gently into fresh water at the same temperature. The saltwater is denser: the same amount of space holds more mass. Watch it sink. Cold, salty ocean water can also sink. This map shows horizontal motion at 1,000 m, not the sinking itself.',key:'Try the saltwater demo in the Classroom lesson · HYCOM model at 1,000 m',source:'/hidden-rivers/folio/#classroom'},
  {place:'denmark',layer:'currents',depth:1000,title:'What changes when glaciers melt?',text:'Melting land ice adds fresh water to the ocean. At the same temperature, fresher water is less dense than saltier water. It can help form a lighter surface layer and make mixing with deeper water harder. Temperature matters too. This current map is not a prediction of future melting.',key:'Freshening changes density · this map does not measure meltwater',source:'https://sos.noaa.gov/datasets/ocean-circulation-conveyor-belts/'},
  {place:'agulhas',depth:0,title:'Turning and sinking are different motions',text:'Look for the loops near this current. Ocean eddies are rotating flows. Swirling a jar can show rotation; adding denser saltwater shows sinking. A real ocean has both, along with wind, tides and moving water shaped by Earth’s rotation and the seabed.',key:'Gold marks faster horizontal flow · color does not show salt or oxygen',source:'https://oceanexplorer.noaa.gov/ocean-fact/currents/'},
  {place:'global',layer:'currents',title:'A connected ocean supports life',text:'Water takes up oxygen near the surface. Sinking and mixing can carry it deeper, where animals use it. Nutrients released as organisms decay can return toward sunlight through upwelling and mixing, helping tiny plants grow. Ships, floats and satellites each reveal part of this connected system.',key:'Ask: what could change if water mixed less? · satellites do not photograph deep currents',source:'/hidden-rivers/folio/#classroom'},
 ]},
 {id:'ocean',title:'Rivers beneath the surface',subtitle:'The Agulhas Current, from the surface to 2,000 m',thumb:'ocean',steps:[
  {place:'agulhas',depth:0,title:'A current turning back on itself',text:'South of Africa, the Agulhas bends back toward the Indian Ocean. Follow the curved flow and the rings to its west. Gold marks faster water in this model snapshot.',key:'Speed in m/s · HYCOM model analysis',source:'https://www.aoml.noaa.gov/phod/altimetry/cvar/agu/'},
  {place:'agulhas',depth:500,title:'Five hundred metres down',text:'The geography stays fixed while the velocity field changes. These are horizontal currents at 500 m, shown through the sea surface. The depth scale remains 1×.',key:'500 m below sea level · no vertical exaggeration'},
  {place:'agulhas',depth:1000,title:'The pattern below the visible ocean',text:'At 1,000 m, compare the position of the strongest flow with the surface layer. Satellite photographs cannot show this motion; the depth field comes from HYCOM.',key:'1,000 m · source model velocities'},
  {place:'agulhas',depth:2000,title:'Two kilometres beneath the waves',text:'This is the deepest available Agulhas layer in this atlas. The lines follow the selected velocity snapshot. Their display speed is accelerated so the flow can be seen.',key:'2,000 m · instantaneous streamlines, not observed tracks'},
 ]},
 {id:'amazon',title:'Two waters at Manaus',subtitle:'A visible boundary, and the spectra behind it',thumb:'manaus',steps:[
  {place:'manaus',layer:'pca',blend:'brightness',palette:'gold',title:'Meeting of the Waters',text:'At Manaus, Brazil, the dark Rio Negro meets the sediment-rich Solimões. The ordered dark-to-light palette follows weaker to stronger visible reflection. A water-only PCA brings their boundary into view.',key:'PC1 · visible brightness contrast',source:'https://science.nasa.gov/earth/earth-observatory/meeting-of-the-waters-79111/'},
  {place:'manaus',layer:'pca',blend:'contrast',palette:'gold',title:'Brightness is only part of the difference',text:'The second component adds a separate spectral contrast. Its strongest loading here is near-infrared against visible light. Click two water pixels to compare their measured band values.',key:'PC1 + PC2 · common basis across the dated scenes'},
  {place:'manaus',layer:'pca',blend:'brightness',palette:'gold',compare:true,title:'Keep the photograph beside the mathematics',text:'Move the dividing line. The natural-color image and the PCA use the same acquisition, coordinates and cloud mask. The color transformation makes a measured contrast easier to see.',key:'One acquisition · natural color / water PCA'},
  {place:'santarem',layer:'pca',blend:'brightness',palette:'gold',title:'Another meeting, farther downstream',text:'At Santarém, the Tapajós meets the Amazon. Their different optical signatures produce another visible boundary. Each place has its own fitted PCA; component values are not compared across places.',key:'Tapajós / Amazon · independently fitted water PCA',source:'https://eol.jsc.nasa.gov/Collections/EarthObservatory/articles/AmazonTapajosSantarem.htm'},
 ]},
 {id:'reef',title:'Light over a submerged landscape',subtitle:'Lighthouse Reef, the Blue Hole and the Great Barrier Reef',thumb:'blue-hole',steps:[
  {place:'blue-hole',layer:'rgb',title:'The dark circle inside Lighthouse Reef',text:'In natural color, pale reef flats surround a dark circular sinkhole. Light reflected by shallow sand and coral can return through the water. The darker hole has a very different optical signature.',key:'Native blue, green and red bands · 10 m',source:'https://science.nasa.gov/earth/earth-observatory/great-blue-hole-belize-37741/'},
  {place:'blue-hole',layer:'pca',blend:'brightness',palette:'ice',title:'Follow the reflected light',text:'The brightness component separates weak blue-green return from bright shallow-water patterns. These colors reveal optical structure. They do not estimate metres of water depth or coral health.',key:'Water PC1 · bottom, water and illumination all contribute'},
  {place:'reef',layer:'pca',blend:'contrast',palette:'coral',title:'Channels through the Great Barrier Reef',text:'Reef flats and darker channels form a branching submerged landscape. The second component adds differences in spectral shape to the brightness pattern. Compare with natural color before interpreting a boundary.',key:'PC1 + PC2 · teal / coral spectral palette',source:'https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-2/Looking_out_for_coral_bleaching'},
 ]},
 {id:'atlantic',title:'Fresh water entering the Atlantic',subtitle:'The Amazon plume and the North Brazil Current',thumb:'ocean',steps:[
  {place:'amazon-plume',layer:'salinity',title:'The river keeps going after the coast',text:'The Amazon’s fresh water spreads across the sea surface. The pale part of this SMAP retrieval has lower salinity; deep blue has higher salinity. This is a dated surface measurement at a broad ocean scale.',key:'SMAP surface salinity · 15 July 2024 · psu',source:'https://oceanwatch.noaa.gov/cwn/products/sea-surface-salinity-near-real-time-smap.html'},
  {place:'amazon-plume',layer:'currents',title:'The current beside the plume',text:'Switch to the seasonal circulation. Satellite-tracked drifters contribute to this monthly mean current field at about 15 m. It provides circulation context, not a trajectory for the separately dated salinity image.',key:'NOAA drifter climatology · 15 m · historical monthly mean'},
 ]},
 {id:'carolina',title:'Cape Fear, from river to sea',subtitle:'Fayetteville, Wilmington and the Carolina coast',thumb:'wilmington',steps:[
  {place:'fayetteville',layer:'rgb',title:'A narrow river through Fayetteville',text:'The Cape Fear is still narrow here. The satellite shows its course through the city and surrounding land. The moving marks indicate drainage direction; this is not a measured river-speed map.',key:'Sentinel-2 · HydroRIVERS downstream direction'},
  {place:'wilmington',layer:'pca',blend:'brightness',palette:'gold',title:'The river widens into an estuary',text:'Below Wilmington, the water’s optical signature varies across channels, shoals and the coast. The brightness palette follows weaker to stronger visible reflection. Sediment, shallow bottom, water properties and atmosphere can all affect that return.',key:'Water PC1 · brightness, not a turbidity concentration'},
  {place:'outer-banks',layer:'pca',blend:'contrast',palette:'coral',title:'Water on both sides of the islands',text:'The barrier islands separate Pamlico Sound from the Atlantic. Follow the inlets and shoals in the spectral image, then compare the same view in natural color.',key:'PC1 + PC2 · sound, shoals and ocean'},
  {place:'gulf-stream',layer:'currents',title:'The Gulf Stream beyond Hatteras',text:'Offshore, the Gulf Stream turns away from the coast. This drifter-derived climatology shows the broad current rather than an estuary-scale flow or today’s conditions.',key:'15 m · monthly mean ocean circulation'},
 ]},
 {id:'world',title:'Across the open ocean',subtitle:'Circulation around a planet of water',thumb:'ocean',steps:[
  {place:'global',layer:'currents',title:'The connected ocean',text:'Trace the broad currents around the globe. These lines are calculated from the monthly mean velocities of satellite-tracked drifters. Line count does not measure the volume of water.',key:'NOAA Global Drifter Program · 15 m'},
  {place:'bahamas',layer:'currents',depth:200,title:'Through the Florida Straits',text:'A depth-resolved model field shows the flow at 200 m between Florida and the Bahamas. Its dated model analysis differs from the historical drifter climatology used in the world view.',key:'HYCOM · 200 m · model analysis'},
  {place:'denmark',layer:'currents',depth:1000,title:'Between Greenland and Iceland',text:'The available Denmark Strait layer is 1,000 m below sea level. Inspect its direction and speed against the surrounding geography. The atlas does not infer a complete three-dimensional circulation from this single layer.',key:'HYCOM · 1,000 m · one available depth'},
  {place:'point-nemo',layer:'currents',title:'Far from every coast',text:'Point Nemo lies in the remote South Pacific. The monthly drifter mean shows broad circulation here; empty cells remain empty where this display has no valid source velocity.',key:'Point Nemo · 15 m drifter climatology'},
 ]},
];
