import test from 'node:test';import assert from 'node:assert/strict';import {Window} from 'happy-dom';
const ui=await import('../../src/scripts/calculus-lab.mjs').catch(()=>({}));
import {lessons} from '../../src/lib/calculus.mjs';
function fixture(){assert.equal(typeof ui.initializeCalculus,'function');const window=new Window({url:'http://localhost/calculus/'});window.document.body.innerHTML='<section data-calculus></section>';return {window,app:ui.initializeCalculus(window.document),root:window.document.querySelector('[data-calculus]')};}
test('every chapter renders its own visual, live mathematics, and a working prediction exercise',()=>{const f=fixture();for(const l of lessons){f.app.setLesson(l.id);assert.equal(f.app.state.lesson,l.id);assert.ok(f.root.querySelector('svg'));assert.ok(f.root.querySelector('.katex'));assert.doesNotMatch(f.root.querySelector("[data-readout]").textContent,/NaN|undefined|Infinity/);f.root.querySelector(`[data-answer="${l.correct}"]`).click();assert.match(f.root.querySelector('[data-feedback]').textContent,/Correct/);}f.window.happyDOM.abort();});
test('controls, actions and reset share a state; corner stays undefined',()=>{const f=fixture(),set=(key,value)=>{const el=f.root.querySelector(`[data-control="${key}"]`);el.value=value;el.dispatchEvent(new f.window.Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));};set('x','2');set('h','.2');assert.equal(f.app.state.result.slope,4);f.root.querySelector('[data-action]').click();assert.equal(f.app.state.params.h,.1);set('fn','abs');set('x','0');assert.equal(f.app.state.result.slope,null);assert.match(f.root.querySelector('[data-readout]').textContent,/does not exist/i);f.root.querySelector('[data-reset]').click();assert.equal(f.app.state.params.fn,'square');f.window.happyDOM.abort();});
test('keyboard chart input updates equations; hash navigation and next lesson work',()=>{const f=fixture();f.root.querySelector('[data-coordinate-plot]').dispatchEvent(new f.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.ok(f.app.state.params.x>1);assert.match(f.root.querySelector('[data-live-math]').textContent,/1.05/);f.root.querySelector('[data-next]').click();assert.equal(f.app.state.lesson,'product');assert.equal(f.window.location.hash,'#product');f.window.happyDOM.abort();});
test('compact experiment picker and animation respect state and reduced motion',()=>{const f=fixture(),picker=f.root.querySelector('[data-lesson-select]');assert.ok(picker);picker.value='logs';picker.dispatchEvent(new f.window.Event('change',{bubbles:true}));assert.equal(f.app.state.lesson,'logs');f.app.setLesson('slope');assert.equal(picker.value,'slope');let callback;f.window.requestAnimationFrame=cb=>{callback=cb;return 1;};f.window.cancelAnimationFrame=()=>{};f.root.querySelector('[data-animate]').click();callback(0);callback(3000);assert.equal(f.root.querySelector('[data-animate]').getAttribute('aria-pressed'),'true');assert.ok(f.app.state.params.x>=-2&&f.app.state.params.x<=2);callback(6000);assert.equal(f.root.querySelector('[data-animate]').getAttribute('aria-pressed'),'false');f.window.matchMedia=()=>({matches:true});f.root.querySelector('[data-animate]').click();assert.match(f.root.querySelector('[data-gesture]').textContent,/Reduced motion/);f.window.happyDOM.abort();});
test('plot accessibility bounds match reachable controls and boundary displays remain finite',()=>{const f=fixture();for(const l of lessons){f.app.setLesson(l.id);const svg=f.root.querySelector('[data-coordinate-plot]'),x=l.controls.find(c=>c.key==='x');if(svg){assert.equal(Number(svg.getAttribute('aria-valuemin')),x.min);assert.equal(Number(svg.getAttribute('aria-valuemax')),x.max);}for(const c of l.controls.filter(c=>!c.options)){for(const v of [c.min,c.max]){f.app.setLesson(l.id);const input=f.root.querySelector(`[data-control="${c.key}"]`);input.value=String(v);input.dispatchEvent(new f.window.Event('input',{bubbles:true}));assert.equal(f.root.querySelector('[data-error]').hidden,true);assert.doesNotMatch(f.root.querySelector('[data-visual]').innerHTML,/NaN|Infinity/);}}}f.window.happyDOM.abort();});
