import test from 'node:test';
import assert from 'node:assert/strict';
const m=await import('../../src/lib/calculus.mjs').catch(()=>({}));
const close=(a,b,tol=1e-9)=>assert.ok(Math.abs(a-b)<tol,`${a} ≠ ${b}`);
function calc(id,p){assert.equal(typeof m.calculate,'function');return m.calculate(id,p);}
test('secants converge, but the absolute-value corner has no derivative',()=>{const a=calc('slope',{fn:'square',x:2,h:.1}),b=calc('slope',{fn:'square',x:2,h:.01});close(a.slope,4);close(a.secant,4.1);assert.ok(Math.abs(b.secant-b.slope)<Math.abs(a.secant-a.slope));const c=calc('slope',{fn:'abs',x:0,h:.1});assert.equal(c.slope,null);close(c.left,-1);close(c.secant,1);});
test('product change includes the finite corner term; differential does not',()=>{const r=calc('product',{x:2,h:.3});close(r.actual,r.first+r.second+r.corner);close(r.actual-r.linear,.09);close(r.slope,5);});
test('chain rule multiplies local sensitivities and preserves sign at negative x',()=>{const r=calc('chain',{x:-2,h:.01});close(r.inner,5);close(r.innerSlope,-4);close(r.outerSlope,.2);close(r.slope,-.8);close(r.actual,Math.log(1+(-1.99)**2)-Math.log(5));});
test('log differences are exact ratios; percentage approximation is not equality',()=>{const r=calc('logs',{x:2,pct:50,base:Math.E});close(r.actual,Math.log(1.5));close(r.linear,.5);close(r.slope,.5);const b=calc('logs',{x:2,pct:50,base:10});close(b.actual,Math.log(1.5)/Math.log(10));assert.throws(()=>m.calculate('logs',{x:0,pct:1,base:10}));assert.throws(()=>m.calculate('logs',{x:2,pct:-100,base:10}));assert.throws(()=>m.calculate('logs',{x:2,pct:1,base:1}));});
test('partials satisfy Euler homogeneity and total differential converges',()=>{const p={x:4,y:3,alpha:.4,dx:.2,dy:-.1},r=calc('partials',p);close(r.fx*p.x+r.fy*p.y,r.value);const s=calc('partials',{...p,dx:.02,dy:-.01});assert.ok(Math.abs(s.actual-s.linear)<Math.abs(r.actual-r.linear)/50);close(r.elasticity,.4);});
test('directional derivative uses a unit direction; saddle curvature changes sign',()=>{const a=calc('gradient',{x:1,y:1,angle:45,shape:'bowl'});close(a.directional,2*Math.sqrt(2));const b=calc('gradient',{x:0,y:0,angle:90,shape:'saddle'});close(b.directional,0);close(b.curvature,-2);});
test('Taylor errors show expected orders and do not claim global accuracy',()=>{const a=calc('taylor',{x:1,h:.2,fn:'log'}),b=calc('taylor',{x:1,h:.1,fn:'log'});assert.ok(Math.abs(b.error1)<Math.abs(a.error1)/3);assert.ok(Math.abs(b.error2)<Math.abs(a.error2)/6);close(a.curvature,-1);});
test('log-profit optimum obeys first and second order conditions',()=>{const r=calc('optimize',{x:3,c:4});close(r.slope,0);close(r.optimum,3);assert.ok(r.curvature<0);close(r.gain,0);});
test('accumulation and derivative recover the integrand; signed area reverses',()=>{const a=calc('integral',{x:2,h:.1});close(a.value,8/3);close(a.slope,4);close(a.actual,(2.1**3-8)/3);const b=calc('integral',{x:-2,h:.1});close(b.value,-8/3);});
test('all admissible defaults and boundary controls are finite and deterministic',()=>{assert.equal(m.lessons.length,9);for(const l of m.lessons){for(const p of [l.defaults,...l.controls.flatMap(c=>c.options?[]:[{...l.defaults,[c.key]:c.min},{...l.defaults,[c.key]:c.max}])]){const a=m.calculate(l.id,p);assert.deepEqual(a,m.calculate(l.id,p));for(const v of Object.values(a))if(typeof v==='number')assert.ok(Number.isFinite(v));}}});
