import test from 'node:test';
import assert from 'node:assert/strict';
import {PROFORMA_FIELDS,illustrativeProForma,calculatePropertyProForma as calc,payment,annualIrr,proFormaSensitivity} from '../../src/lib/property-proforma.mjs';
import {scenarioDocument,parseScenario,proFormaReport,proFormaCsv,createProFormaWorkbook} from '../../src/lib/property-proforma-export.mjs';
const close=(a,b,tol=1e-7)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
export function fixture(patch={}){const a=Object.fromEntries(PROFORMA_FIELDS.map(([,key,,min])=>[key,min]));return {...a,units:1,purchasePrice:100000,rentMonthly:1000,amortYears:10,loanTermYears:10,refiAmortYears:10,refiTermYears:10,holdYears:1,exitPrice:100000,exitCapPct:5,discountPct:10,exitMethod:'price',...patch};}
test('all-cash hand calculation separates NOI, equity, reserve, capex and exit',()=>{const r=calc(fixture());close(r.annual[0].noi,12000);close(r.sources.equity,100000);close(r.returns.irrPct,12);close(r.returns.npv,-100000+112000/1.1);close(r.returns.equityMultiple,1.12);assert.equal(r.annual[0].dscr,null);const reserve=calc(fixture({cashReserve:5000,capexAnnual:1000}));close(reserve.sources.equity,105000);close(reserve.exit.net,105000);close(reserve.annual[0].cashFlow,116000);});
test('zero interest loan amortization and exit balance reconcile to hand calculations',()=>{const r=calc(fixture({loanAmount:80000}));close(payment(80000,0,120),80000/120);close(r.annual[0].debtService,8000);close(r.exit.debtPayoff,72000);close(r.returns.irrPct,60);close(r.annual[0].dscr,1.5);close(r.annual[0].cashOnCashPct,20);close(r.sources.equity+r.sources.loan,r.uses.total);});
test('interest-only ends before amortization and does not postpone maturity',()=>{const r=calc(fixture({holdYears:3,loanAmount:80000,interestPct:6,ioMonths:12,loanTermYears:2}));close(r.annual[0].principal,0);close(r.annual[0].debtService,4800);close(r.monthly[12].payment,payment(80000,6,120));assert.ok(r.annual[1].balloon>0);close(r.annual[2].debtService,0);close(r.exit.debtPayoff,0);assert.equal(r.returns.irrPct,null);});
test('refinance at original maturity replaces balloon once and creates new schedule',()=>{const r=calc(fixture({holdYears:3,loanAmount:80000,loanTermYears:2,refiYear:2,refiValue:120000,refiLtvPct:75,refiCostsPct:2}));close(r.annual[1].balloon,0);close(r.annual[1].refinancePayoff,64000);close(r.annual[1].refinanceLoan,90000);close(r.annual[1].refinanceNet,24200);close(r.annual[2].debtService,9000);close(r.exit.debtPayoff,81000);});
test('maturity coinciding with disposition has exactly one loan payoff',()=>{const r=calc(fixture({loanAmount:80000,loanTermYears:1}));close(r.annual[0].balloon,72000);close(r.exit.debtPayoff,0);close(r.annual[0].cashFlow,32000);});
test('downtime spans years; fixed costs continue; income-cap exit uses forward NOI',()=>{const r=calc(fixture({holdYears:2,downtimeMonths:15,vacancyPct:10,managementPct:10,taxAnnual:1000,rentGrowthPct:10,expenseGrowthPct:5,exitMethod:'cap',exitCapPct:5}));close(r.annual[0].effectiveIncome,0);close(r.annual[0].noi,-1000);close(r.annual[1].effectiveIncome,13200*.75*.9);close(r.exit.forwardNoi,14520*.9*.9-1102.5);close(r.exit.value,r.exit.forwardNoi/.05);});
test('IRR rejects ambiguous roots and no-equity scenarios',()=>{assert.equal(annualIrr([-100,230,-132]).value,null);assert.equal(annualIrr([0,100]).value,null);close(annualIrr([-100,-10,150]).value,17.5765067213126,1e-9);});
test('bounds prevent impossible financing and invalid optional refinance timing',()=>{for(const patch of [{purchasePrice:NaN},{loanAmount:100001},{holdYears:1.5},{refiYear:1},{interestPct:-1},{ioMonths:120}])assert.throws(()=>calc(fixture(patch)),RangeError);});
test('sensitivity center reproduces base model and monotone cash-only value effects',()=>{const a=fixture(),s=proFormaSensitivity(a);close(s[4].npv,calc(a).returns.npv);assert.ok(s[0].npv<s[4].npv&&s[4].npv<s[8].npv);});
test('portable scenario strips unknown metadata and reports escape user strings',()=>{const d=scenarioDocument({name:'<img src=x onerror=alert(1)>',origin:'user',assumptions:fixture(),property:{address:'=SUM(1,2)',parcelId:'X',token:'secret'}});assert.equal(d.property.token,undefined);assert.deepEqual(parseScenario(JSON.stringify(d)).assumptions,fixture());assert.throws(()=>parseScenario('{"schema":"other"}'));assert.doesNotMatch(proFormaReport(d),/<img src=x/);assert.match(proFormaCsv(d),/'=SUM/);});
test('workbook exports live formulas for debt, returns and assumptions without external links',async()=>{const doc=scenarioDocument({name:'Hand fixture',assumptions:fixture({holdYears:3,loanAmount:80000,loanTermYears:2,refiYear:2,refiValue:120000,refiLtvPct:75,refiCostsPct:2})});const w=await createProFormaWorkbook(doc);assert.equal(w.getWorksheet('Debt').rowCount,361);assert.match(w.getWorksheet('Debt').getCell('E14').formula,/PMT/);close(w.getWorksheet('Returns').getCell('B5').result,81000);assert.match(w.getWorksheet('Returns').getCell('B9').formula,/NPV/);assert.equal(w.getWorksheet('Inputs').getCell('B2').value,100000);const bytes=await w.xlsx.writeBuffer();assert.ok(bytes.byteLength>30000);});
test('stress values outside model bounds are unavailable without hiding the valid base case',()=>{const a=fixture({exitMethod:'cap',exitCapPct:.1}),s=proFormaSensitivity(a);assert.ok(s.some(x=>x.npv===null));close(s[4].npv,calc(a).returns.npv);});
